import React, { useState } from 'react';
import { ChevronDown, HelpCircle } from 'lucide-react';

const FAQS = [
  {
    question: 'What is Kokoro Voice Studio?',
    answer:
      'Kokoro Voice Studio is a state-of-the-art online AI text-to-speech workstation powered by the lightweight Kokoro-82M neural model. It generates natural, human-like speech across 60 voices in English, Japanese, French, Korean, Mandarin, Spanish, Hindi, Italian, and Portuguese.',
  },
  {
    question: 'Is Kokoro Voice Studio free to use?',
    answer:
      'Yes! Kokoro Voice Studio includes a generous free monthly quota of 20,000 characters with complete access to all 60 voices, audio mastering presets, and SRT subtitle export. Users can also upgrade to Unlimited Pro with VIP codes.',
  },
  {
    question: 'Can I use generated speech for YouTube, TikTok, and Podcasts?',
    answer:
      'Yes, all audio generated by Kokoro Voice Studio can be exported as studio-quality 24kHz MP3 or WAV files, along with synchronized .SRT subtitle files ready to import directly into CapCut, Premiere Pro, or DaVinci Resolve.',
  },
  {
    question: 'What languages and accents are supported by Kokoro TTS?',
    answer:
      'Kokoro supports 9+ international languages including English (US & UK), French, Japanese, Korean, Mandarin Chinese, Spanish, Hindi, Italian, and Brazilian Portuguese with native phonemization (G2P).',
  },
  {
    question: 'How does the Voice Blender work?',
    answer:
      'The Voice Blender mathematically interpolates neural voice embeddings between any two selected voices at custom percentage ratios, producing completely unique hybrid vocal identities tailored for your projects.',
  },
];

export const SeoFaq: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <section className="max-w-4xl mx-auto w-full py-8 px-2 select-none">
      <div className="text-center mb-8">
        <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-blue-500/10 text-blue-600 dark:text-blue-400 text-xs font-semibold uppercase tracking-wider mb-2">
          <HelpCircle className="w-3.5 h-3.5" />
          <span>Frequently Asked Questions</span>
        </div>
        <h2 className="text-xl sm:text-2xl font-extrabold text-slate-900 dark:text-white tracking-tight">
          Everything You Need to Know About Kokoro TTS
        </h2>
      </div>

      <div className="space-y-3">
        {FAQS.map((faq, idx) => {
          const isOpen = openIndex === idx;
          return (
            <div
              key={idx}
              className="bg-white/80 dark:bg-slate-800/80 backdrop-blur-md border border-slate-200/80 dark:border-slate-700/80 rounded-2xl overflow-hidden transition-all shadow-sm"
            >
              <button
                onClick={() => setOpenIndex(isOpen ? null : idx)}
                className="w-full p-4 sm:p-5 text-left flex items-center justify-between gap-4 cursor-pointer"
              >
                <span className="font-bold text-xs sm:text-sm text-slate-800 dark:text-slate-200">
                  {faq.question}
                </span>
                <ChevronDown
                  className={`w-4 h-4 text-slate-400 shrink-0 transition-transform duration-200 ${
                    isOpen ? 'rotate-180 text-blue-600 dark:text-blue-400' : ''
                  }`}
                />
              </button>

              {isOpen && (
                <div className="px-4 sm:px-5 pb-4 sm:pb-5 text-xs text-slate-500 dark:text-slate-400 leading-relaxed border-t border-slate-100 dark:border-slate-700/60 pt-3">
                  {faq.answer}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
};
export default SeoFaq;
